spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/TestDB
    username: root
    password: mariadb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
